name: Create Release

on:
  push:
    branches:
      - main
jobs:
  monkeyversion:
    name: Get Monkey365 version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get current version
        id: monkey365version
        shell: pwsh
        run: |
          $manifest = Test-ModuleManifest -Path "./monkey365.psd1"
          $prerelease = $manifest.PrivateData.PSData['Prerelease']
          If ($prerelease -and $prerelease.StartsWith('-')){
              $version = ("{0}{1}" -f $manifest.version,$prerelease)
          }
          else{
              $version = ("{0}-{1}" -f $manifest.version,$prerelease)
          }
          $releaseName = ("Monkey365 v{0}" -f $version)
          "monkey365version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "releasename=$releaseName" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      - name: Get current date
        id: date
        run: echo "today=$(date +'%Y-%m-%d_%H%M%S')" >> $GITHUB_OUTPUT
      - name: Set release
        id: release_message
        run: |
          echo "message=Thanks for follow [Monkey365](https://github.com/silverhack/monkey365)!." >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: comnoco/create-release-action@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.monkey365version.outputs.monkey365version }}
          release_name: ${{ steps.monkey365version.outputs.releasename }}
          body: ${{ steps.release_message.outputs.message }}
          draft: true
          prerelease: false
      # Create a zip of the folder
      - name: Create ZIP file of the folder
        if: steps.create_release.outcome  == 'success'
        run: |
          mkdir -p build
          git archive --format zip --output ./build/monkey365.zip main
          gh release upload ${{ steps.monkey365version.outputs.monkey365version }} ./build/monkey365.zip
          sha256sum ./build/monkey365.zip | awk '{print $1}' > ./build/monkey365.zip.sha256
          gh release upload ${{ steps.monkey365version.outputs.monkey365version }} ./build/monkey365.zip.sha256
          sha512sum ./build/monkey365.zip | awk '{print $1}' > ./build/monkey365.zip.sha512
          gh release upload ${{ steps.monkey365version.outputs.monkey365version }} ./build/monkey365.zip.sha512
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
